version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: secure
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "3339:5432"